services:
  backend_db:
    image: postgres:14-alpine
    volumes:
      - db_volume:/var/lib/postgresql/data
    env_file:
      - backend/env/.env
    ports:
      - 5432:5432
    networks:
      - backend_network


  backend_checkers:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    expose:
      - 8000
    env_file:
      - backend/env/.env
    restart: on-failure
    networks:
      - backend_network
    depends_on:
      - backend_db

  frontend:
    build:
      context: ./frontend
    expose:
      - 1234
    volumes:
      - ./frontend:/app
    networks:
      - backend_network

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - frontend
      - backend_checkers
    networks:
      - backend_network
    volumes:
      - ./backend:/app/
      - ./frontend:/app


networks:
  backend_network:
    driver: bridge

volumes:
  db_volume:
