services:
  backend_db:
    image: postgres:14-alpine
    volumes:
      - db_volume:/var/lib/postgresql/data
    env_file:
      - backend/env/.env
    ports:
      - 5432:5432
    networks:
      - backend_network


  backend_checkers:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    ports:
      - 8000:8000
    env_file:
      - backend/env/.env
    restart: on-failure
    networks:
      - backend_network
    depends_on:
      - backend_db

  frontend:
    build:
      context: ./frontend
    ports:
      - 1234:1234
    volumes:
      - ./frontend:/app
    networks:
      - backend_network



networks:
  backend_network:
    driver: bridge

volumes:
  db_volume: